### ISSUE TITLE
Viewport size

### ISSUE THREAD

**Issue by jnpetersen** [wassy92x/lovelace-ha-dashboard#1]
For the sidebar, on smaller displays life Amazon Fire Tablets, the sidebar doesn't appear.  Its because its screen size is width is 1024 and you have it set statically to that.  Maybe you can modify the code so the user can specify at what screen size to hide the side bar?

**Comment by wassy92x** [comment]
In the new release v1.1.0 this possibility is added. You can now use the config-key `sidebar.screenMinWidth` to set the minimum screen width at which the sidebar will be shown.

But if your screen is 1024px width, I don't think that you have to change the default setting, because I also corrected a bug in screen width calculation.
